name: Validate Code (React + FastAPI)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (React)
        working-directory: ./client
        run: npm install

      - name: Build React
        working-directory: ./client
        run: npm run build

  build-fastapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./fastapi-backend
        run: pip install -r requirements.txt

      - name: Validate FastAPI imports
        working-directory: ./fastapi-backend
        run: python -m py_compile $(git ls-files '*.py')
